language: node_js
node_js:
- '6.10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: jnmiller@cryptofreak.org
  api_key:
    secure: PjweBWKJ1r0PdmXeZUX8CvC6OK3HN+TYdP6enf6LFD2Zw8cXpbsu8S8qfF1b74H7p+kDx+PMBR8GwYAsvdptyEUC9x2z086SO/zMmEZkNqnSovfvUG1ZpD2+hbHtfGWKNxEeusQVG4KLniK/RznQbFs6EB+szgpxwvqlXyHB8W0rNMZIg1fOSmGF9zViiSxG8E9rZfKO9ZwTN5O8YrmTQmnzkqjrXzHGYK3SGipx0u48TTpOL6outUdI7ygseSUp8ul9vzy1iyOvYHRrZoQz3j+ePzUgQ8Hfy5dtr65o6i6xLCoEkxh8aM1ATT5QSvKuyOzqJbPzlc35yMVUSZVuPCwKgd3b8jjavouhWvmH9fO+vU3EsxFdFPCLQGks3yNQDOuPxdlDNiAYClaoNjO05VzOAGKPolg1DV6xgZQOsXQ/No+bjxiVW0ldtuIg1Fp1kJF5FEWuzXhP8GuuerN58UxUO67WLS5GMoAjB9bOUJIORoOdA+axfKU+jInA7ZxFe2ubHXUVpWiFWjBRTPdE8nACwmncnX31ZqY9b1FXl1akQxw5COMC9jdsCko1C2uIl9+4oI0iDNA1MNoD1UnDlZo7SEgmoXZBUdGXVb2AqsogKnsXsSPNPneGuyQkMMtwf79MwL8slgyDyyC1/nFndSrDuTFHYyIuxUdhUHaU7DU=
  on:
    tags: true
    repo: ladenedge/mcc-serviceability
